id: IA3722FDB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T16:25:13+00:00'
last_modified: '2022-06-07T14:13:21.614393+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18739
  title: བོད་སྐད་བརྡ་སྤྲོད་སྐོར་གྱི་དཔེ་རྒྱུན་དཀོན་རིགས་འགའ་ཕྱོགས་གཅིག་ཏུ་བསྒྲིགས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D32F:
      image_group_id: I8LS18741
      title: ''
      total_pages: 534
      order: 1
      base_file: D32F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
