id: P001728
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18739
  title: བོད་སྐད་བརྡ་སྤྲོད་སྐོར་གྱི་དཔེ་རྒྱུན་དཀོན་རིགས་འགའ་ཕྱོགས་གཅིག་ཏུ་བསྒྲིགས་པ།
  author: ''
  volumes:
    461a03bddb6442c0b611d4010f4cbffd:
      image_group_id: I8LS18741
      title: ''
      volume_number: 1
      total_pages: 534
      base_file: v001.txt
